export const agents = {
  strategy: { label: "Strategy", color: "bg-[var(--agent-strategy)]/10 text-[var(--agent-strategy)] border-[var(--agent-strategy)]/20" },
  data: { label: "Data Analyst", color: "bg-[var(--agent-data)]/10 text-[var(--agent-data)] border-[var(--agent-data)]/20" },
  search: { label: "Search", color: "bg-[var(--agent-search)]/10 text-[var(--agent-search)] border-[var(--agent-search)]/20" },
  research: { label: "Research", color: "bg-[var(--agent-research)]/10 text-[var(--agent-research)] border-[var(--agent-research)]/20" },
} as const;

export type AgentKey = keyof typeof agents;

export function detectAgents(prompt: string): AgentKey[] {
  const p = prompt.toLowerCase();
  const out: AgentKey[] = [];
  if (/analy[sz]e|data|metric|number|kpi/.test(p)) out.push("data");
  if (/strateg|plan|roadmap|grow/.test(p)) out.push("strategy");
  if (/find|search|document|look/.test(p)) out.push("search");
  if (/market|competitor|industry|trend/.test(p)) out.push("research");
  return out.length ? out : ["strategy", "data"];
}

export const dataSources = [
  { name: "Q3-Financials.xlsx", type: "Excel", status: "Active", updated: "2h ago" },
  { name: "Customer-Survey.csv", type: "CSV", status: "Syncing", updated: "Just now" },
  { name: "Market-Report.pdf", type: "PDF", status: "Active", updated: "1d ago" },
  { name: "Sales DB", type: "Postgres", status: "Active", updated: "Live" },
  { name: "Legacy-Export.csv", type: "CSV", status: "Error", updated: "3d ago" },
];

export const reports = [
  { name: "Q3 Revenue Insights", agent: "Data Analyst", date: "Nov 12, 2025" },
  { name: "Competitor Landscape 2025", agent: "Research", date: "Nov 10, 2025" },
  { name: "Go-to-Market Strategy", agent: "Strategy", date: "Nov 08, 2025" },
  { name: "Customer Churn Analysis", agent: "Data Analyst", date: "Nov 05, 2025" },
];

export const team = [
  { name: "Aarav Mehta", email: "aarav@acme.io", role: "Admin", status: "Active" },
  { name: "Priya Shah", email: "priya@acme.io", role: "Analyst", status: "Active" },
  { name: "Daniel Kim", email: "daniel@acme.io", role: "Researcher", status: "Active" },
  { name: "Sara Lin", email: "sara@acme.io", role: "Viewer", status: "Invited" },
];

export const auditLogs = [
  { ts: "2025-11-12 14:22", user: "aarav@acme.io", action: "Connected S3 bucket", status: "Success" },
  { ts: "2025-11-12 13:48", user: "priya@acme.io", action: "Ran query: Q3 revenue", status: "Success" },
  { ts: "2025-11-12 11:10", user: "system", action: "SAML sync", status: "Success" },
  { ts: "2025-11-11 18:02", user: "daniel@acme.io", action: "Uploaded Market-Report.pdf", status: "Success" },
  { ts: "2025-11-11 09:30", user: "sara@acme.io", action: "Login attempt", status: "Failed" },
];

// Dashboard KPI data
export const kpis = [
  { label: "Total Revenue", value: "$2.84M", change: +18.4, unit: "QoQ", color: "var(--agent-strategy)" },
  { label: "Active Users", value: "1,247", change: +9.2, unit: "MoM", color: "var(--agent-data)" },
  { label: "AI Queries Today", value: "847", change: +34.1, unit: "vs yesterday", color: "var(--agent-search)" },
  { label: "Churn Rate", value: "2.1%", change: -0.4, unit: "QoQ", color: "var(--agent-research)" },
];

// Revenue trend (last 7 months)
export const revenueTrend = [
  { month: "May", revenue: 1.82, queries: 420 },
  { month: "Jun", revenue: 1.95, queries: 510 },
  { month: "Jul", revenue: 2.1, queries: 580 },
  { month: "Aug", revenue: 2.25, queries: 640 },
  { month: "Sep", revenue: 2.38, queries: 710 },
  { month: "Oct", revenue: 2.6, queries: 780 },
  { month: "Nov", revenue: 2.84, queries: 847 },
];

// Agent usage breakdown
export const agentUsage = [
  { agent: "Data Analyst", queries: 312, pct: 37, color: "var(--agent-data)" },
  { agent: "Strategy", queries: 228, pct: 27, color: "var(--agent-strategy)" },
  { agent: "Search", queries: 185, pct: 22, color: "var(--agent-search)" },
  { agent: "Research", queries: 122, pct: 14, color: "var(--agent-research)" },
];

// Recent AI insights generated by agents
export const recentInsights = [
  {
    id: "1",
    agent: "data" as const,
    title: "Q3 Revenue Spike Detected",
    summary: "Enterprise tier drove +18.4% QoQ growth. FinServ vertical now 32% of new ARR.",
    time: "2 min ago",
    priority: "high" as const,
  },
  {
    id: "2",
    agent: "research" as const,
    title: "Competitor Pricing Shift",
    summary: "Rival A dropped SMB pricing by 15%. Recommend reviewing mid-market positioning.",
    time: "18 min ago",
    priority: "medium" as const,
  },
  {
    id: "3",
    agent: "strategy" as const,
    title: "APAC Expansion Opportunity",
    summary: "Singapore & Tokyo markets show 27% YoY AI spend growth. Q1 entry window open.",
    time: "1h ago",
    priority: "medium" as const,
  },
  {
    id: "4",
    agent: "search" as const,
    title: "Churn Signal in Survey Data",
    summary: "3 enterprise accounts flagged low NPS in Customer-Survey.csv. Immediate CSM action advised.",
    time: "3h ago",
    priority: "high" as const,
  },
];
